### ISSUE TITLE
Feature request: festivals sorted by region

### ISSUE THREAD

**Issue by leccelecce** [dot4qu/Lineup-List#16]
As I'm planning on adding a few festivals in Europe, I thought something like the below might be helpful. It felt like doing it this way it would keep the UI a bit cleaner than adding another dropdown or region checkboxes.

I have a PR ready for this but before sending it thought it made sense to show the output it generates.

![image](https://user-images.githubusercontent.com/24962424/176036450-70711785-cb73-42d9-8881-0470262268be.png)

**Comment by dot4qu** [comment]
Originally i went with the single simple dropdown because there weren't that many festivals in it. Now that it's grown so much, switching to a text-entry textbox that filtered results in a dropdown has been getting higher on my todo list, but I've been busy with other projects.

I'm okay with this change as it doesn't change much, but depending on the direction I go for implementing the filtering behavior it might get scrapped again if it's to much of a pain to keep integrated. I haven't looked into the best way to do this within handlebars yet, I've only done it within a react app or with vanilla JS, so I can't speak to what the result will be.

Thanks for the idea and contribution though!

**Comment by leccelecce** [comment]
OK, no problem if you want to replace it in future with something better.
