### ISSUE TITLE
Allow specifying artist via Spotify artist URI instead of just name

### ISSUE THREAD

**Issue by leccelecce** [dot4qu/Lineup-List#38]
Another proposed PR I would like to run by you before working on.

As I've added a Spotify API artist search check to my lineup scrapers, I came across the varying challenges you've already experienced with not always getting the right artist (noting the current logic in https://github.com/dot4qu/Lineup-List/blob/dev/src/spotify-helper.ts#L127 that attempts a lowercase name check against top 15 results, and if no matches picks the first).

I've come across a couple of cases where an artist doesn't have a unique name (Cici) or even a case-unique name (e.g. Cici, CICI, CiCi). I can work out the correct one, but then have no way of ensuring that passes through via the lineup file. Similarly this would have helped avoid the Maneskin UTF-8 issue around accented characters.

I was going to propose a possible solution: allowing the passing in of an artist in a lineup file as the URI from the Spotify artist object e.g. `spotify:artist:4kI8Ie27vjvonwaB2ePh8T`.

It would be a relatively straightforward check in the warm cache script to simply check if the artist name starts with `spotify:artist:` and if so, query the Spotify API artist endpoint rather than the search one. Alternatively could pipe-separate the first value in the csv e.g. `CiCi|spotify:artist:4kI8Ie27vjvonwaB2ePh8T,2` which might make debugging a little easier. If the pipe-character was detected and a valid Spotify URI found, the code could use that over the artist name. Either way, it would be backward-compatible with existing lineup files.

This might seem like a bit of a fudge rather than upgrading the line-up file format to something that supports a more complex object hierarchy as you proposed on #25 - but that's relatively speaking a much bigger change.

**Comment by dot4qu** [comment]
Not ignoring these I promise! Super hectic time for me right now sorry, moving internationally in a couple weeks and trying to  get that situated + getting two board designs finished to get them back in time from China.

So I've also thought about this as a solution to the issue that I fixed with the code that you identified correctly. It sat on the todo list for a while and then I eventually scrapped it because with the new logic to iterate until it found an exact match I hadn't seen any more errors between artists.

I still think it's a good idea to add the functionality, but I don't want to do it at the expense of the readability of the file. I like having the artist names in there so I can hop in and add daily lineups, remove some artists that get dropped, etc. I wouldn't be able to do that if it was just URIs.

That being said, an easy fix for that is just including it in the comma-delimited list like we've talked about for some other additions as well, i.e.: `The Chemical Brothers,spotify:artist:xxxxxxxxxx,2`

I'm kind of annoying about this format though and I'd rather not keep shoving more information into just a CSV basically. I think this is the perfect kind of thing to include if the lineup files switch to a more structured format like yaml though:
```
artist:
- name: The Chemical Brothers
- uri: xxxxxxxxxxxxxxxx
- days:
    - 1
    - 2
```

You get the point. Have you seen any other instances of artists not matching up correctly from your scraper?

**Comment by leccelecce** [comment]
Happy to put together a PR for a yaml lineup format. Looks like using the `yaml` library it's fairly trivial to parse files. To maintain backward compatibility, could just search for both lineup extensions (festival_year.yml or .txt) and prefer the .yml one if it exists.

One point re your proposed format above - I think this might make the lineup files a bit more difficult to review, because given you are listing artists and then assigning them to days, this means there is no easy way to just read a file and see who is on what day. I can see how you're trying to support artists who appear on multiple days but is it worth the increased complexity when reading a file when this is relatively rare? I would have thought the lesser of two evils would be just to list the artist out for each day they appear on. But happy if that's the way you want to go.

You previously suggested this format on #25 (which also covered externalising the festival data, but one step at a time):

```
display_name: Nos Alive
slug: nosalive
year: 2022
days: 0
artists:
  - blah
  - blah
  - blah
```

How about combined (though I would probably ignore the festival data initially and just continue filename-based loading):

```
display_name: Nos Alive
slug: nosalive
year: 2022
days:
  - day:
      name: '1'
      artists:
        - artist:
            name: The Chemical Brothers
            spotify_uri: xxxxxxxxxxxxxx
        - artist:
            name: The Strokes
            spotify_uri: xxxxxxxxxxxxxx
  - day:
      name: '2'
      artists:
        - artist:
            name: The Cure
            spotify_uri: xxxxxxxxxxxxxx
        - artist:
            name: The XX
            spotify_uri: xxxxxxxxxxxxxx

```

URI would be optional.

This does open up lots of other possibilities, such as having both friendly names and actual dates for festival days (particularly relevant for say All Points East where it takes place over multiple weeks) and any other metadata that adds value.

**Comment by dot4qu** [comment]
Yeah so that's where I was a little hung up when briefly thinking through the format the first time around. I couldn't decide if I liked having `days` be the top level key and the artists all underneath it but I don't actually see why it would be bad. I think your second example is pretty solid. One note I would have is that each list item should just have a key as the top level item, then fields below it. So it would look more like

```
display_name: Nos Alive
slug: nosalive
year: 2022
days:
  - 1:
    display_name: Friday, June 16th
    artists:
      - The Chemical Brothers:
        spotify_uri: xxxxxxxxxxxxxx
      - The Strokes:
        spotify_uri: xxxxxxxxxxxxxx
  - 2
    display_name: Saturday, June 17th
    artists:
      - The Cure:
        spotify_uri: xxxxxxxxxxxxxx
      - The XX:
        spotify_uri: xxxxxxxxxxxxxx
```

I'm kind of ehh on using the artist display name as the key, but the only two other decent options I can think of are either using the spotify uri or using some sort of slug:
```
      - the_strokes:
        display_name: The Strokes
        spotify_uri: xxxxxxxxxxxxxx
```
I don't like the former because that mandates the use of spotify URI and I'd like it to be optional, and I don't like the latter because it's annoying amount of extra work to slugify the artist names when I'm inputting from lineup posters (I recognize you don't have either of these problems from your scraping script).

>  could just search for both lineup extensions (festival_year.yml or .txt) and prefer the .yml one if it exists.
Yep agreed, no need to go through the past ones and change much. Depending on if there's more detail added to the yaml files like festival dates, or actual day names/dates versus just numbers, the frontend render will have to gracefully handle the case of not having all the data for older .txt based lineups.

To your last point:
> This does open up lots of other possibilities, such as having both friendly names and actual dates for festival days 
I don't actually know why I'm only using 1, 2, and 3. I started using the actual days for one or two festivals and then completely forgot about them. The day numbers are stored as strings anyway I'm pretty sure so there's probably nothing stopping switching to more detailed days strings already.

**Comment by leccelecce** [comment]
> I don't actually know why I'm only using 1, 2, and 3. I started using the actual days for one or two festivals and then completely forgot about them. The day numbers are stored as strings anyway I'm pretty sure so there's probably nothing stopping switching to more detailed days strings already.

Just a very quick point on this - the day goes into the redis key I think i.e. `festivals:name_year:<day>`. So if you start putting wacky things in there it'll probably upset it.

**Comment by leccelecce** [comment]
I have got something working which you can now see as a draft PR on #46. At the moment it effectively just replicates the current format in YAML, with the only addition being the Spotify URI (i.e. days work the same way as they do currently)

> One note I would have is that each list item should just have a key as the top level item, then fields below it. So it would look more like

I just tried changing the code in my PR to have your YAML layout and am struggling to quickly see how I get it to parse the artist name or day as a key into an object property. The way I've done it is probably naive as to what you can do with YAML, but it does work. If you're keen that I fix that I will take a look at it again.
